### ISSUE TITLE
Error in demerits calculation

### ISSUE THREAD

**Issue by louridas** [bramstein/typeset#12]
According to the TeX Book, p. 98, and Breaking Paragraphs into Lines, the demerits of a line with a penalty -10000 < penalty < 0 should be:

demerits = Math.pow(options.demerits.line + badness, 2) - Math.pow(node.penalty, 2);

instead of 

demerits = Math.pow(options.demerits.line + badness - node.penalty, 2);

which is currently the case in:

https://github.com/bramstein/typeset/blob/master/src/linebreak.js#L168

**Comment by bramstein** [comment]
Thanks, they were indeed incorrect. I've fixed it.
