### ISSUE TITLE
Chinese Support

### ISSUE THREAD

**Issue by PointerTan** [bramstein/typeset#18]
It seems that this algorithm doesn't support Chinese

**Comment by bramstein** [comment]
I think the algorithm itself can handle Chinese, but my implementation probably does not. I'm open for pull requests if it is something you want to add.

**Comment by PointerTan** [comment]
@bramstein Thanks for your reply

**Comment by ivanwonder** [comment]
Chinese do not have space between word, compare 'Hello world' with '世界，你好'. I think it is more like an inter-letter space.
