### ISSUE TITLE
Broken link in readme.md

### ISSUE THREAD

**Issue by justinpenner** [bramstein/typeset#29]
Here's an updated link to the Knuth and Plass article:
https://onlinelibrary.wiley.com/doi/abs/10.1002/spe.4380111102

**Comment by alerque** [comment]
This has already been reported and somebody has tried to fix it in #28. The contribution has not been accepted yet.

**Comment by justinpenner** [comment]
Ah, my mistake. I only looked in the Issues tab before posting.
