### ISSUE TITLE
Do line lengths work?

### ISSUE THREAD

**Issue by PhilterPaper** [bramstein/typeset#31]
While trying to figure out why I couldn't set more than two line lengths in the Perl version (Text::KnuthPlass), PhilterPaper/text-knuthplass#7, I decided to try out the lineLengths setting in your Flatlands.html example. As shipped, it is [], so I tried one, two, and three values (apparently in Points, or possibly Pixels). It seems to usually only affect the very first line, and usually not any other, although some lists of values seemed to have strange effects several paragraphs down, including loss of right-justification. Note that the first paragraph is very short, usually only two lines.

1. Can anyone confirm that `lineLengths` actually work, and give a brief example (such as with Flatland.html)?
2. Are `lineLengths` supposed to start over at each paragraph, or does it just keep going? If I give 5 lengths, it appears to continue into the second paragraph (as ragged right), and then the third paragraph and on are back to full width.

I want to make sure I'm using `lineLengths` correctly, and that the Javascript (typeset) code works, before I go through a lot of labor cross-checking against the Perl (and C) version I recently picked up support for. It would be very disappointing to find that I can only give two line lengths (e.g., indented and normal paragraph lines), and not be able to do image and aside insets, or non-rectangular paragraph shapes, as promised in the documentation.

**Comment by PhilterPaper** [comment]
On the subject of checking against some standard algorithm, I _do_ have Knuth's book on the TeX program. However, my understanding is that this version of paragraph shaping (Knuth-Plass algorithm) is quite enhanced for purposes of TeX use (it will handle equations, etc.) and may thus not be a good candidate for a reference. I also, of course, have the _typeset_ JS implementation, but at this point I'm not sure it's complete (e.g., the line length problem). Can anyone recommend a good, clean,
_verified_ fully functional implementation, such as in Python or even pseudo-code?

**Comment by shreevatsa** [comment]
For what it's worth, the TeX implementation of `line_break` does not worry about equations etc; there's a separate part of the program that handles math formulas (converting (math) mlists into (horizontal) hlists), so that the line-breaking part only has to deal with regular lists (without caring about whether some of its entries may be math-related).

**Comment by PhilterPaper** [comment]
I notice that the line lengths _do_ seem to work in examples/article/ ("flow" example), so the basic code may be OK. It's still apparently bad in the Perl port Text::KnuthPlass, but suggests that a later fix to _this_ package may need to be applied to _that_ one.

**Comment by PhilterPaper** [comment]
After playing some more with line lengths in the _flatland_ example, I think I've figured out what it's doing. The `lineLengths` array is a one-shot usage, with elements (line lengths) being consumed as used. It is not recycled when used up, or restarted at each paragraph. Thus it is a bit different in behavior from the Perl implementation. Dimensions such as line lengths are in pixels.
* Empty list given: the browser is queried as to what the line length is (say, 544px). When an `<img>` is processed, the width of the image (px) is subtracted from the global line length, and the number of such lines calculated from the leading and image height (px). The shortened line length is pushed onto `lineLengths` that number of times, plus one full length. Thus, the image must be at the top of a paragraph (I don't think it will work in the middle). 
* Non-empty list given: it uses one element of `lineLengths` per line, until it has been consumed. At an image float, I think it should be using the standard short line, but this doesn't seem consistently done. When `lineLengths` has been emptied, it looks like it handles it as above for the rest of the document.

Paragraph indentations are done by pushing a 30px empty 'box' to the front of all but the first paragraph (in a section), so Knuth-Plass handles it in the normal way and the line always starts at the left margin. A lot of stuff is done outside of Knuth-Plass, and unique (hard coded) to this example, but it's still an interesting exercise. It should be possible to figure out a general left- or right-float flow in Perl.

I don't have it working quite consistently, but at least I can see how it _is_ using the `lineLengths` array, passing either a given or a generated list of lengths to the Knuth-Plass routine. Some Javascript trickery _outside of the Knuth-Plass routine_ is done to flow text around a floated image (by generating short line lengths, regardless of whether the list was being used originally). My original concern about whether it was using the list at all appears to have been answered, so I will close this ticket.
